## NumPy Datatypes

In [1]:
import numpy as np

# Creating an array with a specific data type
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)  # Output: int32

int32


## NumPy Attributes

In [2]:
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)
print("Item Size:", arr1.itemsize)
print("Total Bytes:", arr1.nbytes)
print("Transpose:\n", arr1.T)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int32
Item Size: 4
Total Bytes: 24
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


## Creating Numpy Arrays

### Arrays from list

In [3]:
arr_from_list = np.array([1, 2, 3, 4, 5])
arr_from_list

array([1, 2, 3, 4, 5])

### Using built functions 

#### 3X3 array filled with zeroes

In [4]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 3X3 array filled with ones

In [5]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Array from 0 to 10 (exclusive) with step 2

In [6]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

#### Array with 5 evenly spaced values from 0 to 1

In [7]:
linspace_array = np.linspace(0, 10, 5)
linspace_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### 2x2 array with random values from uniform distribution

In [8]:
random_array = np.random.rand(2, 2)
random_array

array([[0.66403033, 0.15686417],
       [0.11126287, 0.80818165]])

### Reshaping Arrays

#### Array from 0 to 8

In [9]:
original_array = np.arange(9)
original_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
reshaped_array = original_array.reshape((3, 3))  # Reshaping to a 3x3 array
reshaped_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Numpy random seed

In [29]:
np.random.seed(42)

# Generate random numbers
random_numbers = np.random.rand(3)
random_numbers

array([0.37454012, 0.95071431, 0.73199394])

## Viewing Arrays and Matrices

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Printing array using print()
print("Array:")
print(arr)
print()


Array:
[[1 2 3]
 [4 5 6]]



In [31]:
print("String Representation:")
print(np.array_str(arr))
print()

String Representation:
[[1 2 3]
 [4 5 6]]



In [32]:
# Shape and size
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print()

Shape: (2, 3)
Size: 6
Dimensions: 2



In [33]:
# Accessing elements
print("Accessing elements:")
print("First row:", arr[0])
print("First element of the second row:", arr[1, 0])
print()

Accessing elements:
First row: [1 2 3]
First element of the second row: 4



In [34]:
# Transpose
print("Transpose:")
print(arr.T)

Transpose:
[[1 4]
 [2 5]
 [3 6]]
