In [1]:
import numpy as np

# Manipulating Arrays 

## reshape()

In [25]:
arr = np.arange(3,12)

reshaped_arr = arr.reshape((3, 3))
print(reshaped_arr)

[ 3  4  5  6  7  8  9 10 11]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Indexing and Slicing:

In [23]:
print(arr[1])          # First element
print(arr[1:4])        # Slicing
print(arr[:1])         # Second column

4
[4 5 6]
[3]


## Element-wise Operations: 

In [26]:
print(arr)
result = arr * 2
print(result) 

[ 3  4  5  6  7  8  9 10 11]
[ 6  8 10 12 14 16 18 20 22]


## Aggregation Functions: 

In [28]:
ar1 = np.array([[1, 2], [3, 4]])
print(ar1)
print(np.sum(ar1))     # Sum of all elements
print(np.max(ar1, axis=0))  # Maximum along each column

[[1 2]
 [3 4]]
10
[3 4]


## Broadcasting: 

In [31]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


## Concatenation and Splitting:

In [32]:
arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[5, 6]])
concatenated = np.concatenate((arr4, arr5), axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]


## Flattening: 

In [33]:
arr = np.array([[1, 2], [3, 4]])
flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4]


## Sorting

In [34]:
arr = np.array([[3, 2], [1, 4]])
sorted_arr = np.sort(arr, axis=None)  # Sort flattened array
print(sorted_arr)

[1 2 3 4]


## resizing

In [35]:
arr = np.array([[1, 2], [3, 4]])
arr.resize((2, 3))
print(arr)

[[1 2 3]
 [4 0 0]]


## appending

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
appended_arr = np.append(arr1, arr2)
print(appended_arr)

[1 2 3 4 5 6]


## inserting

In [38]:
arr = np.array([1, 2, 3, 4, 5])
inserted_arr = np.insert(arr, 2, [10, 20])
print(inserted_arr)

[ 1  2 10 20  3  4  5]


## deleting

In [42]:
arr = np.array([1, 2, 3, 4, 5])
deleted_arr = np.delete(arr, [0,1,2,3,4])
print(deleted_arr)

[]


## masking

In [46]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr % 2 == 0
filtered_arr = arr[mask]
print(filtered_arr)

[2 4]


## stacking

In [47]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2))
print(stacked_arr)

[[1 2 3]
 [4 5 6]]
